### PR TITLE
feat: GCS Based Templates Should Support All SparkSQL CSV Options

### PR DESCRIPTION
**Pull request by nj1973**
This request changes all Python templates that read from or write to Cloud Storage to support all CSV options supported by Spark. Listed here: https://spark.apache.org/docs/latest/sql-data-sources-csv.html#data-source-option

Because I didn't want to add the same code in multiple places I've refactored all templates to use central functions for adding CSV options to dataframes.

Example change for reading from Cloud Storage
Previous code:
```
        input_data: DataFrame

        if input_file_format == constants.FORMAT_PRQT:
            input_data = spark.read \
                .parquet(input_file_location)
        elif input_file_format == constants.FORMAT_AVRO:
            input_data = spark.read \
                .format(constants.FORMAT_AVRO_EXTD) \
                .load(input_file_location)
        elif input_file_format == constants.FORMAT_CSV:
            input_data = spark.read \
                .format(constants.FORMAT_CSV) \
                .option(constants.HEADER, True) \
                .option(constants.INFER_SCHEMA, True) \
                .load(input_file_location)
        elif input_file_format == constants.FORMAT_JSON:
            input_data = spark.read \
                .json(input_file_location)
```
New code:
```
        spark_read_options = spark_options_from_template_args(args, constants.GCS_BT_INPUT_SPARK_OPTIONS)
        input_data = ingest_dataframe_from_cloud_storage(
            spark, input_file_format, input_file_location, spark_read_options
        )
```

And same technique for writing to Cloud Storage.
Previous code:
```

        if gcs_output_format == constants.FORMAT_PRQT:
            writer \
                .parquet(gcs_output_location)
        elif gcs_output_format == constants.FORMAT_AVRO:
            writer \
                .format(constants.FORMAT_AVRO) \
                .save(gcs_output_location)
        elif gcs_output_format == constants.FORMAT_CSV:
            writer \
                .option(constants.HEADER, True) \
                .csv(gcs_output_location)
        elif gcs_output_format == constants.FORMAT_JSON:
            writer \
                .json(gcs_output_location)
```
New code:
```
        spark_write_options = spark_options_from_template_args(args, constants.GCS_TO_GCS_OUTPUT_SPARK_OPTIONS)
        persist_dataframe_to_cloud_storage(writer, gcs_output_format, gcs_output_location, spark_write_options)
```

This removes a lot of duplication.
The Spark options themselves are driven by constants, see `SPARK_OPTIONS`.
The tmeplate options are also driven by constants mapping them back to Spark options, e.g: `GCS_BQ_INPUT_SPARK_OPTIONS`

After merging this I need to raise an equivalent issue for the Java templates.

### CODE REVIEW

**Comment by shashank-google** [comment]
please review optional parameters in readmes

**Comment by nj1973** [comment]
@shashank-google , I've modified several READMEs to highlight new attributes as optional as requested.
Unit and integration tests have run cleanly.

**Review by NiloFreitas — CHANGES_REQUESTED** [review]
Please consider this refactor of this PR, where I simplified the code a little bit.
It is in this branch:
https://github.com/GoogleCloudPlatform/dataproc-templates/tree/feature/issue-532-csv-options-refactor

**Comment by nj1973** [comment]
@NiloFreitas I have created a new PR based on your suggested modifications on branch [issue-532-csv-options-refactor](https://github.com/GoogleCloudPlatform/dataproc-templates/tree/feature/issue-532-csv-options-refactor).
When we are done with the other PR I'll delete this one.

**Pull request closed without merging**
