### PR TITLE
Launching PySpark Dataproc Template using Vertex AI

### LINKED ISSUE #104: FR: Create solution to allow launching of templates using Vertex AI

### PR DESCRIPTION
**Pull request by NiloFreitas**
Adds an example Python notebook and documentation demonstrating how to launch Dataproc Templates from Vertex AI.

This first example notebook shows how to build a Vertex AI Pipeline to run a Dataproc Template using the DataprocPySparkBatchOp Kubeflow component.

Closes #104

### CODE REVIEW

**Comment by ppaglilla** [comment]
I haven't been able to test the notebook submission myself, but it looks great to me!

**Review by ppaglilla — APPROVED** [review]

**Review by surjits254 — COMMENTED** [review]
LGTM

**Review by surjits254 — APPROVED** [review]

**Comment by shashank-google** [comment]
More testing will be done, before it is merged into main.

**Comment by surjits254** [comment]
Tested notebook with internal IP using NAT. LGTM

**Pull request merged**
