### PR TITLE
fix: script for running spark jobs on dataproc cluster

### PR DESCRIPTION
**Pull request by kkulczak**
Removed `--version` argument for `gcloud dataproc jobs submit spark` command.

This argument is not supported with this command: https://cloud.google.com/sdk/gcloud/reference/dataproc/jobs/submit/spark

### CODE REVIEW

**Comment by shashank-google** [comment]
@kkulczak 
I am not sure of this pull request, you probably have misunderstood something.
The argument `version` is part of gcloud dataproc **batches** submit spark as below
https://cloud.google.com/sdk/gcloud/reference/dataproc/batches/submit/spark#--version

You were probably trying to submit job to dataproc VM cluster (not dataproc serverless)
To submit to DP cluster you need to `export JOB_TYPE="CLUSTER"`

**Comment by kkulczak** [comment]
@shashank-google 
I agree with you and I'm modifying command which is used in case of `JOB_TYPE="CLUSTER"`
I'm fixing the command with which submits jobs to the cluster.
`gcloud dataproc jobs submit spark` do not have `--version` argument.


Command for spark serverless stays the same.
[[link]](https://github.com/GoogleCloudPlatform/dataproc-templates/pull/770/files#diff-2abb43cde7fa7ff5d901ebdc0649ac90b241321d81b7f739b45ecf38019e64baR135)

**Comment by shashank-google** [comment]
@kkulczak 
I guess I mis-read something when I was reviewing it last time.
I had discussion with @hhasija we should be good to accept this change (as long as integration tests are not failing).
@hhasija please do the needful

**Comment by hhasija** [comment]
merged as a part of new PR 

https://github.com/GoogleCloudPlatform/dataproc-templates/pull/783

**Review by hhasija — COMMENTED** [review]
LGTM

**Pull request closed without merging**
