### PR TITLE
Snowflake to GCS

### PR DESCRIPTION
**Pull request by vanshaj-bhatia**

### CODE REVIEW

**Comment by snrssc** [comment]
Review in progress. Testing from my side

**Comment by snrssc** [comment]
Observation: Password is printed in logs

**Comment by vanshaj-bhatia** [comment]
> Observation: Password is printed in logs

The toString() of SnowflakeToGCSConfig.java makes the password field as REDACTED while returning.
For all the templates, the arguments are getting logged at DataProcTemplate.java, which logs secrets/ passwords as well.

https://github.com/GoogleCloudPlatform/dataproc-templates/blob/e08bf76143df7eb161fd335b4915427d7b85136a/java/src/main/java/com/google/cloud/dataproc/templates/main/DataProcTemplate.java#L107-L109

@shashank-google please suggest if we can remove this?

**Comment by vanshaj-bhatia** [comment]
> > Observation: Password is printed in logs
> 
> The toString() of SnowflakeToGCSConfig.java makes the password field as REDACTED while returning. For all the templates, the arguments are getting logged at DataProcTemplate.java, which logs secrets/ passwords as well.
> 
> https://github.com/GoogleCloudPlatform/dataproc-templates/blob/e08bf76143df7eb161fd335b4915427d7b85136a/java/src/main/java/com/google/cloud/dataproc/templates/main/DataProcTemplate.java#L107-L109
> 
> @shashank-google please suggest if we can remove this?

@snrssc @shashank-google 
We can also make use of Secret Manager to store the secrets/ passwords, and just pass the secret id from execution command. The templates can then fetch the secret value during runtime. Please suggest.

**Comment by shashank-google** [comment]
> > Observation: Password is printed in logs
> 
> The toString() of SnowflakeToGCSConfig.java makes the password field as REDACTED while returning. For all the templates, the arguments are getting logged at DataProcTemplate.java, which logs secrets/ passwords as well.
> 
> https://github.com/GoogleCloudPlatform/dataproc-templates/blob/e08bf76143df7eb161fd335b4915427d7b85136a/java/src/main/java/com/google/cloud/dataproc/templates/main/DataProcTemplate.java#L107-L109
> 
> @shashank-google please suggest if we can remove this?

We don't want to remove this at this point.

**Review by snrssc — APPROVED** [review]

**Pull request merged**
