### PR TITLE
fix: Fix for kafka message offset

### PR DESCRIPTION
**Pull request by chakresh84**

### CODE REVIEW

**Comment by vanshaj-bhatia** [comment]
@chakresh84 The integration tests are failing even with the above changes. This
is the today's adhoc run on this branch: https://dataproctemplatesci.com/blue/organizations/jenkins/dataproc-templates-build%2Fad-hoc%2Fintegration-tests-java/detail/integration-tests-java/432/pipeline

**Comment by chakresh84** [comment]
> @chakresh84 The integration tests are failing even with these changes. This is the today's adhoc run on this branch: https://dataproctemplatesci.com/blue/organizations/jenkins/dataproc-templates-build%2Fad-hoc%2Fintegration-tests-java/detail/integration-tests-java/432/pipeline

@vanshaj-bhatia The build history for February (1st feb to 23rd feb) shows only one failure(9 feb), indicating consistent success. If the changes don't resolve the issue, we should investigate the Dataproc infrastructure setup and configuration (including Kafka, templates, messages, and the Jenkins build frequency/history). If the problem stems from the code itself, we would likely see more frequent build failures.

**Review by vanshaj-bhatia — CHANGES_REQUESTED** [review]
The fix isn't working. Need to explore more on the intermittent failures of the DStream templates: #907

**Comment by shashank-google** [comment]
@vanshaj-bhatia @chakresh84 
Are we still working on this ?

**Comment by shashank-google** [comment]
marking this as closed, since fix is not working.
Please reopen with updated changes.

**Pull request closed without merging**
