### PR TITLE
feat: Refactor JDBC source notebooks

### PR DESCRIPTION
**Pull request by nj1973**
This PR introduces library code under the notebooks directory in order to have a single place for engine specific code and logic around setting Spark SQL JDBC options. The library code is found in `notebooks/util`.

Actions completed by this PR:

- Dedupe Oracle SQL for table identification from 3 notebooks into library code
- Dedupe Oracle SQL for primary key identification from 3 notebooks into library code
- Dedupe Oracle SQL for partition columns identification from 3 notebooks into library code
- Fix incorrect Oracle SQL for primary key and partition columns identification
- Fix variation in MySQL code for table identification is different in two notebooks, one uses `INFORMATION_SCHEMA.Tables` other uses `show tables`
- Fixed bug in display of Spanner primary keys (assumption that dict in same order as list)
- MySQL PK read partitioning only driven by PKs on a single column, Oracle code picked first column of any PK. The Oracle logic was flawed and has been sync'd with MySQL logic.
- Added support for user provided read partition keys.
- Added variable for `ORACLE_SCHEMA` which means connections are no longer forced to use the schema account. This is more realistic in an Oracle environment.
- Added variable for `OJDBC_JAR` to prevent du[plication throughout the notebooks.
- Updated SQLAlchemy calls to be compatible with SQLAlchemy 2.0.

Actions not included:

- Not included MSSQL templates. I'll raise a secondary issue for MSSQL templates once this is complete. The PR was becoming too large and a blocker for review.

Items I'd like assistance with from the reviewer:

- I've created some notebook unit tests for the new library code but it's not clear whether/how I should add these in Jenkins
- To test Spanner notebooks I had to add pip install of google.cloud.spanner client. It is unclear how the notebooks were working previously, I have not changed any Spanner specific code. Any ideas welcome.

I have created a GCE instance with Oracle and PostgreSQL instances which can be used for testing. Details will be provided to the reviewer if required.

### CODE REVIEW

**Comment by NiloFreitas** [comment]
Reviewing this this week

**Comment by nj1973** [comment]
There's been a lot of change to the notebooks changed by this PR recently and I've had to resolve a lot of conflicts. I need to do a full re-test.

**Comment by nj1973** [comment]
I've re-tested the Oracle to BigQuery notebook after dealing with a few merge conflicts. Should be ready for review again.

**Review by surjits254 — APPROVED** [review]
LGTM

**Pull request merged**
